// <auto-generated />
using System;
using ExamAI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExamAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExamAI.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataUpload")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_upload")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErroProcessamento")
                        .HasColumnType("text")
                        .HasColumnName("erro_processamento");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_sha256");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nome_arquivo");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<string>("StatusProcessamento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status_processamento");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_arquivo");

                    b.HasKey("Id");

                    b.HasIndex("HashSha256");

                    b.HasIndex("PacienteId");

                    b.HasIndex("StatusProcessamento");

                    b.ToTable("documentos", (string)null);
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.Exame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataColeta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_coleta");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("Laboratorio")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("laboratorio");

                    b.Property<string>("MedicoSolicitante")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("medico_solicitante");

                    b.Property<int?>("TipoExameId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_exame_id");

                    b.HasKey("Id");

                    b.HasIndex("DataColeta");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("TipoExameId");

                    b.ToTable("exames", (string)null);
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.Paciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.ToTable("pacientes", (string)null);
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.ResultadoExame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ExameId")
                        .HasColumnType("uuid")
                        .HasColumnName("exame_id");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Parametro")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("parametro");

                    b.Property<decimal?>("ReferenciaMax")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("referencia_max");

                    b.Property<decimal?>("ReferenciaMin")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("referencia_min");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Unidade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unidade");

                    b.Property<decimal?>("ValorNumerico")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_numerico");

                    b.Property<string>("ValorTexto")
                        .HasColumnType("text")
                        .HasColumnName("valor_texto");

                    b.HasKey("Id");

                    b.HasIndex("ExameId");

                    b.HasIndex("Parametro");

                    b.HasIndex("Status");

                    b.ToTable("resultados_exame", (string)null);
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.TipoExame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("tipos_exame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Hematologia",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(5723),
                            Nome = "Hemograma Completo"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Bioquímica",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6135),
                            Nome = "Glicemia"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Lipidograma",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6138),
                            Nome = "Colesterol Total"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Lipidograma",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6139),
                            Nome = "HDL"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Lipidograma",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6140),
                            Nome = "LDL"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Lipidograma",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6141),
                            Nome = "Triglicerídeos"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Função Renal",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6143),
                            Nome = "Ureia"
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Função Renal",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6144),
                            Nome = "Creatinina"
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Função Hepática",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6145),
                            Nome = "TGO/AST"
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Função Hepática",
                            CreatedAt = new DateTime(2026, 2, 3, 1, 27, 24, 856, DateTimeKind.Utc).AddTicks(6146),
                            Nome = "TGP/ALT"
                        });
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.Documento", b =>
                {
                    b.HasOne("ExamAI.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Documentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.Exame", b =>
                {
                    b.HasOne("ExamAI.Domain.Entities.Documento", "Documento")
                        .WithMany("Exames")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamAI.Domain.Entities.TipoExame", "TipoExame")
                        .WithMany("Exames")
                        .HasForeignKey("TipoExameId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Documento");

                    b.Navigation("TipoExame");
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.ResultadoExame", b =>
                {
                    b.HasOne("ExamAI.Domain.Entities.Exame", "Exame")
                        .WithMany("Resultados")
                        .HasForeignKey("ExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exame");
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.Documento", b =>
                {
                    b.Navigation("Exames");
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.Exame", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ExamAI.Domain.Entities.TipoExame", b =>
                {
                    b.Navigation("Exames");
                });
#pragma warning restore 612, 618
        }
    }
}
